apiVersion: v1
kind: Service
metadata:
  name: ng-three-gl-web
  labels:
    app: ng-three-gl
spec:
  selector:
    app: ng-three-gl
    tier: web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 35.197.251.126
